// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADYQwznZn23RppuplMGu5OekQP0uMAWTI',
    appId: '1:430350869935:web:13711c1d4dc63ec3337b5a',
    messagingSenderId: '430350869935',
    projectId: 'library-resource-management',
    authDomain: 'library-resource-management.firebaseapp.com',
    storageBucket: 'library-resource-management.firebasestorage.app',
    measurementId: 'G-EB4MTFFPL3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlPgyK6xJIJ_T8VTHK9q17TmeaBzGm9CE',
    appId: '1:430350869935:android:3146ee47b8ff454c337b5a',
    messagingSenderId: '430350869935',
    projectId: 'library-resource-management',
    storageBucket: 'library-resource-management.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTh18qO0YyRnG9cWJzUhnAc0o8hP7Uz7s',
    appId: '1:430350869935:ios:5c8b3772c2b42700337b5a',
    messagingSenderId: '430350869935',
    projectId: 'library-resource-management',
    storageBucket: 'library-resource-management.firebasestorage.app',
    iosBundleId: 'com.example.libraryResourceManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTh18qO0YyRnG9cWJzUhnAc0o8hP7Uz7s',
    appId: '1:430350869935:ios:5c8b3772c2b42700337b5a',
    messagingSenderId: '430350869935',
    projectId: 'library-resource-management',
    storageBucket: 'library-resource-management.firebasestorage.app',
    iosBundleId: 'com.example.libraryResourceManagement',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyADYQwznZn23RppuplMGu5OekQP0uMAWTI',
    appId: '1:430350869935:web:c695a4f8f5f3b47c337b5a',
    messagingSenderId: '430350869935',
    projectId: 'library-resource-management',
    authDomain: 'library-resource-management.firebaseapp.com',
    storageBucket: 'library-resource-management.firebasestorage.app',
    measurementId: 'G-MRF2HVR0V3',
  );
}
